services:
  db:
    image: mysql:9.0
    volumes: 
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"

  web:
    build: .
    command: sh -c 'sleep 10 && python manage.py runserver 0.0.0.0:8000'
    volumes:
      - .:/djangoProject
    ports:
      - "8000:8000"
    env_file:
      .env
    depends_on:
      - db
    

volumes:
  mysql_data:
